homagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('app/', include('homagram_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

homagram_app/urls.py
from django.urls import path
from . import views

app_name = 'homagram_app'

urlpatterns = [
    path('profile/<int:user_id>/', views.users_profiles, name='users_profiles'),
    path('feed_page/', views.feed_page, name='feed'),
    path('send_email/', views.send_email, name='send_email'),
    # path('upload_resume/', views.upload_resume, name='upload_resume'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('delete_resume', views.delete_resume, name='delete_resume'),
]

# htmx_urlpatterns = [
#     # path('upload_resume/', views.upload_resume, name='upload_resume'),
#     path('delete_resume/', views.delete_resume, name='delete_resume'),
# ]
#
# urlpatterns += htmx_urlpatterns

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('login/', views.my_login, name='login'),
    path('logout/', views.my_logout, name='logout'),
    path('change_password/', views.change_password, name='change_password'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_forgot_password/', views.reset_forgot_password, name='reset_forgot_password'),
]

homagram_app/models.py
from django.db import models
from users.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(blank=True, null=True, default=None)
    age = models.IntegerField(blank=True, null=True)
    phone = models.IntegerField(unique=True, blank=True, null=True)
    email = models.EmailField(unique=True, blank=True, null=True)
    title_about_text = models.CharField(max_length=50,blank=True, null=True)
    about_text = models.CharField(max_length=1200, blank=True, null=True)
    profile_photo = models.ImageField(null=True, blank=True, upload_to='img/profile_img', default='img/default_img.jpg')
    about_facts = models.CharField(max_length=100, blank=True, null=True)
    happy_clients = models.IntegerField(default=0)
    projects = models.IntegerField(default=0)
    hours_of_support = models.IntegerField(default=0)
    hard_worker = models.IntegerField(default=0)
    location = models.CharField(max_length=40, blank=True, null=True)
    resume = models.FileField(upload_to='resumes/', blank=True, null=True)
    resume_text = models.CharField(max_length=100, blank=True, null=True)
    pers_website = models.URLField(max_length=200, blank=True, null=True)
    degree = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.email} - Profile"


class SocialMediaLink(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    facebook_link = models.URLField(blank=True, null=True)
    instagram_link = models.URLField(blank=True, null=True)
    skype_link = models.URLField(blank=True, null=True)
    twitter_link = models.URLField(blank=True, null=True)
    linkedin_link = models.URLField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.email} - Social Media Links"

homagram_app/forms.py
from django import forms
from users.models import User
from .models import UserProfile, SocialMediaLink


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'


class UserProfileForm(forms.ModelForm):
    resume = forms.FileField(required=False, widget=forms.FileInput(attrs={'class': "input100"}))

    class Meta:
        model = UserProfile
        fields = [
            'birth_date', 'age', 'phone', 'email', 'about_text',
            'profile_photo', 'about_facts', 'happy_clients', 'projects',
            'hours_of_support', 'hard_worker', 'location', 'resume',
            'title_about_text', 'resume_text', 'pers_website', 'degree',
        ]

        widgets = {
            'birth_date': forms.DateInput(attrs={'class': "input100", 'placeholder': 'YYYY-MM-DD'}),
            'age': forms.NumberInput(attrs={'class': "input100", 'placeholder': 'Enter your age'}),
            'phone': forms.NumberInput(attrs={'class': "input100", 'placeholder': 'Enter phone number'}),
            'email': forms.EmailInput(attrs={'class': "input100", 'placeholder': 'Enter your email'}),
            'about_text': forms.TextInput(attrs={'class': "input100", 'placeholder': 'Tell us about yourself'}),
            'profile_photo': forms.FileInput(attrs={'class': 'input100'}),
            'about_facts': forms.TextInput(attrs={'class': "input100", 'placeholder': 'Facts about you'}),
            'happy_clients': forms.NumberInput(attrs={'class': "input100", 'placeholder': 'Amount of clients'}),
            'projects': forms.NumberInput(attrs={'class': "input100", 'placeholder': 'Amount of projects'}),
            'hours_of_support': forms.NumberInput(attrs={'class': "input100", 'placeholder': 'Amount of hours'}),
            'hard_worker': forms.NumberInput(attrs={'class': "input100", 'placeholder': 'Amount of hard worker'}),
            'location': forms.TextInput(attrs={'class': "input100", 'placeholder': 'Your location'}),
            # 'resume': forms.FileInput(attrs={'class': "input100"}),
            'title_about_text': forms.TextInput(attrs={'class': "input100", 'placeholder': 'Title of about text'}),
            'resume_text': forms.TextInput(attrs={'class': "input100", 'placeholder': 'Title of resume'}),
            'pers_website': forms.TextInput(attrs={'class': "input100", 'placeholder': 'Personal website link'}),
            'degree': forms.TextInput(attrs={'class': "input100", 'placeholder': 'Your degree'}),
        }


class SocialMediaLinkForm(forms.ModelForm):
    class Meta:
        model = SocialMediaLink
        fields = '__all__'

homagram_app/views.py
from django.shortcuts import render, redirect, HttpResponse
# from users.forms import CreateUserForm
# from .forms import UserProfileForm
from django.contrib.auth.decorators import login_required
from users.models import User
from .models import UserProfile, SocialMediaLink
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from homagram import settings
from django.http import JsonResponse
from .forms import UserForm, UserProfileForm, SocialMediaLinkForm
from django.shortcuts import get_object_or_404
from django.contrib import messages


@login_required
def users_profiles(request, user_id):
    user_profile = get_object_or_404(UserProfile, user_id=user_id)
    form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
    users = get_object_or_404(User, id=user_id)
    resume_exists = bool(user_profile.resume)

    if request.method == 'POST':
        resume = request.FILES.get('resume')
        if resume:
            request.user.userprofile.resume = resume
            request.user.userprofile.save()
            return redirect('homagram_app:users_profiles', user_id=request.user.id)

    context = {
        'users': users,
        'form': form,
        'resume_exists': resume_exists,
        'user_profile': user_profile,
        'user': request.user,
    }
    return render(request, 'homagram_app/users_profiles.html', context)


@login_required
def edit_profile(request):
    user_profile = get_object_or_404(UserProfile, user=request.user)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            if 'resume' in request.FILES:
                user_profile.resume = request.FILES['resume']
            form.save()
            return redirect('homagram_app:users_profiles', user_id=user_profile.user_id)
    else:
        form = UserProfileForm(instance=user_profile)

    context = {'form': form,
               'user_profile': user_profile,
               }
    return render(request, 'homagram_app/edit_profile.html', context)


def feed_page(request):
    form = UserForm()
    users = User.objects.filter(is_superuser=False)
    user_profile = get_object_or_404(UserProfile, user=request.user)

    context = {'form': form,
               'users': users,
               'user_profile': user_profile
               }
    return render(request, 'homagram_app/feed_page.html', context)


def send_email(request):
    if request.method == 'POST':
        template = render_to_string('homagram_app/email_template.html', {
            'name': request.POST['name'],
            'email': request.POST['email'],
            'message': request.POST['message']
        })

        email = EmailMessage(
            request.POST['subject'],
            template,
            settings.EMAIL_HOST_USER,
            ['YOUR_EMAIL_GOES_HERE']
        )

        email.fail_silently = False
        email.send()

        return JsonResponse({'status': 'success'})

    return render(request, 'homagram_app/users_profiles.html')


def delete_resume(request):
    # remove_resume = UserProfile.objects.get(id=resume_id)
    user_profile = get_object_or_404(UserProfile, user=request.user.userprofile)
    print('user_profile geeet')
    if request.method == 'POST':
        print('pooost')
        user_profile.resume = None
        print('nonee')
        user_profile.save()
        print('saved')

        # remove_resume.resume.delete()
        return redirect('hoamgram_app:edit_profile')

    context = {
        # 'remove_resume': remove_resume,
        'user_profile': user_profile,
    }

    return render(request, 'homagram_app/edit_profile.html', context)

homagram_app/templates/homagram_app/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Base{% endblock %}</title>

    <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- =======================================================
  * Template Name: iPortfolio
  * Template URL: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/
  * Updated: Mar 17 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->

    <!--=========== for Registration Bootstrap template==============-->
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'registration/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'registration/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'registration/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'registration/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'registration/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'registration/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'registration/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'registration/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'registration/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'registration/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'registration/css/main.css' %}">
<!--===============================================================================================-->

<!--====================htmx link===============-->
<script src="https://unpkg.com/htmx.org@1.5.0/dist/htmx.min.js"></script>





<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"></script>



</head>
<body>
    {% block content %}

    <div id="profile">
        {% include 'homagram_app/users_profiles.html' %}
    </div>

    {% endblock %}

</body>
</html>

homagram_app/templates/homagram_app/edit_profile.html
{% extends 'homagram_app/base.html' %}

{% load static %}

{% block title %}asdf{% endblock %}


{% block content %}


	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'registration/images/bg-01.jpg' %}');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Edit Profile
				</span>
				<form action="{% url 'homagram_app:edit_profile' %}" method="POST" enctype="multipart/form-data" class="login100-form validate-form p-b-33 p-t-5">
					{% csrf_token %}

<!--					<div class="right-side">-->

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.title_about_text }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.birth_date }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>


						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.age }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.pers_website }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.degree }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.phone }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.email }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.about_text }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>


						{% if user.userprofile.profile_photo and user.userprofile.profile_photo.url != '/media/img/default_img.jpg' %}
							<div class="wrap-input100 validate-input">
									<a target="_blank" href="{{ user_profile.profile_photo.url }}">Picture Link</a>

								<span class="focus-input100" data-placeholder="&#xe82a;"></span>
							</div>
						{% else %}
							<div class="wrap-input100 validate-input">
									{{ form.profile_photo }}

								<span class="focus-input100" data-placeholder="&#xe82a;"></span>
							</div>
						{% endif %}

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.about_facts }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.happy_clients }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.projects }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.hours_of_support }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.hard_worker }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.location }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.resume_text }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						{% if user.userprofile.resume %}
						<div class="wrap-input100 validate-input" data-validate = "Upload Resume">
								<a class="resume_link" target="_blank" href="{{ user_profile.resume.url }}">Resume Link</a>

								<form action="{% url 'homagram_app:delete_resume' %}" method="post" enctype="multipart/form-data">
									{% csrf_token %}
									<button type="submit" class="delete_resume">Delete Resume</button>
								</form>
							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>
						{% else %}
							<div class="wrap-input100 validate-input" data-validate = "Upload Resume">
								{{ form.resume }}

							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>
						{% endif %}

<!--					</div>-->

						<div class="container-login100-form-btn m-t-32">
							<button type="submit" class="login100-form-btn">
								Save
							</button>
							<a class="signup_button" href="{% url 'homagram_app:users_profiles' user.id %}">Back</a>
						</div>

				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'registration/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'registration/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/js/main.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"></script>





{% endblock %}

homagram_app/templates/homagram_app/email_template.html
{{message}}

{{email}}

{{name}}

homagram_app/templates/homagram_app/feed_page.html
{% extends 'homagram_app/base.html' %}

{% load static %}

{% block content %}


  <!-- ======= Mobile nav toggle button ======= -->
  <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>


<style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f0f0f0;
        }

        .profile_feed img {
    display: block;
    max-width: 100px; /* Adjust size as needed */
    margin: 0 auto 10px; /* Center and add margin below */
    }

        .profile_feed {
    position: relative;
    padding: 20px;
    border: 1px solid #ddd;
    margin-bottom: 20px;
    background-color: #f9f9f9;
    width: 300px; /* Adjust width as needed */
    overflow: hidden;
    box-sizing: border-box; /* Include padding and border in the element's total width and height */
}

/* Styling the View Profile button */
.view-profile-btn {
    display: block;
    margin-bottom: 10px;
    color: #007bff;
    text-decoration: none;
    font-weight: bold;
}

.view-profile-btn:hover {
    background-color: #0dcaf0;
}

</style>


    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs_inner">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Inner Page</h2>
          <ol>
            <li><a href="{% url 'homagram_app:users_profiles' user.id %}">My Profile</a></li>

<!--            <div class="dropdown">-->
<!--              <button>Profile</button>-->
<!--              <div class="dropdown-options">-->
<!--                <a href="#">Dashboard</a>-->
<!--                <a href="#">Setting</a>-->
<!--                <a href="#">Logout</a>-->
<!--              </div>-->
<!--            </div>-->

            <li><a href="{% url 'users:change_password' %}">Change Password</a></li>
            <li><a href="{% url 'users:logout' %}">Log Out</a></li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

<!--    <section class="inner-page">-->
<!--      <div class="container">-->
<!--        <p>-->
<!--          Example inner page template-->
<!--        </p>-->
<!--      </div>-->
<!--    </section>-->

<!--===========profiles on feed===========-->

{% for user in users %}
    <div class="profile_feed">
        <a href="{% url 'homagram_app:users_profiles' user.id %}" class="view-profile-btn">View Profile</a>

            <img src="{{ user.userprofile.profile_photo.url }}" alt="Profile Picture">

        <h2>{{ user.first_name|title }} {{ user.last_name|title }}</h2>
        <p>{{ user.about }}</p>
    </div>
{% endfor %}


  <!-- ======= Footer ======= -->
  <footer id="footer_inner">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>HomaGram</span></strong>
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/ -->
        Designed by <strong><span>Giorgi Khomasuridze</span></strong>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/typed.js/typed.umd.js' %}"></script>
  <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>


{% endblock %}

homagram_app/templates/homagram_app/upload_resume.html
{% extends 'homagram_app/base.html' %}

{% load static %}

{% block title %}Home - My Site{% endblock %}


{% block content %}

<form method="post" enctype="multipart/form-data" action="{% url 'homagram_app:upload_resume' %}">
    {% csrf_token %}
    <input type="file" name="resume">
    <button type="submit">Upload Resume</button>
</form>


{% endblock %}