homagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('app/', include('homagram_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('login/', views.my_login, name='login'),
    path('logout/', views.my_logout, name='logout'),
    path('change_password/', views.change_password, name='change_password'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_forgot_password/', views.reset_forgot_password, name='reset_forgot_password'),
]

users/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models
from django.core.validators import validate_email
from .choices import GenderChoices


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password=None,
                     **extra_fields):
        # print('register user model save---------------------------------')
        validate_email(email)
        email = self.normalize_email(email)
        user = self.model(email=email,
                          **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email,
                    password=None,
                    **extra_fields):
        # print('register user model save---------------------------------')
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password,
                                 **extra_fields)

    def create_superuser(self, email,
                         password=None,
                         **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password,
                                 **extra_fields)


class User(AbstractUser):
    username = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    mobile_number = models.CharField(max_length=20)
    about = models.CharField(max_length=250)
    age = models.IntegerField(default=0)
    gender = models.CharField(
        max_length=6,
        choices=GenderChoices.choices(),
        blank=True,
        null=True,
        default=None,
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.forms.widgets import PasswordInput, TextInput
from .models import User
from .choices import GenderChoices


class LoginForm(forms.Form):
    email = forms.CharField(label="email", widget=forms.EmailInput(attrs={'class': "input100",
                                                                          'id': 'email',
                                                                          "placeholder": "Email",
                                                                          "type": "email",
                                                                          "name": "email"}))

    password = forms.CharField(label="password", widget=forms.PasswordInput(attrs={'class': "input100",
                                                                                   'id': 'password',
                                                                                   "type": "password",
                                                                                   "name": "password",
                                                                                   'placeholder': 'Password'}))


class CreateUserForm(forms.ModelForm):
    SEX_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input100', 'id': 'password1',
                                                                  'placeholder': 'Password'}))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input100', 'id': 'password2',
                                                                  'placeholder': 'Confirm Password'}))

    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'input100', 'placeholder': 'Email',
                                                           'id': 'email'}))

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input100',
                                                             'placeholder': 'Username',
                                                             'id': 'username'}), required=False)

    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input100',
                                                               'placeholder': 'First Name',
                                                               'id': 'first_name'}))

    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input100',
                                                              'placeholder': 'Last Name',
                                                              'id': 'last_name'}))

    mobile_number = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'input100',
                                                                     'placeholder': 'Phone',
                                                                     'id': 'mobile_number',
                                                                     'minlength': '9', 'maxlength': '9'}))

    about = forms.CharField(widget=forms.TextInput(attrs={'class': 'input100',
                                                          'id': 'about',
                                                          'placeholder': 'About'}))

    gender = forms.ChoiceField(choices=GenderChoices.choices(), widget=forms.Select(attrs={'class': 'input100',
                                                                                           'id': 'sex',
                                                                                           'placeholder': 'Select you gender',
                                                                                           }))

    age = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'input100',
                                                           'placeholder': 'Age',
                                                           'id': 'age',
                                                           }))

    class Meta:
        model = User
        fields = (
            'username', 'first_name', 'last_name', 'email', 'password1', 'password2',
            'mobile_number',
            'about',
            'gender',
            'age',
        )

        exclude = ('is_active', 'is_staff', 'date_joined', 'permission', 'password')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    #
    # def clean_phone(self, *args, **kwargs):
    #     mobile_number = self.cleaned_data.get('phone')
    #     if not mobile_number.isdigit():
    #         raise forms.ValidationError('You must input valid phone number!')
    #     else:
    #         return mobile_number
    #
    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        print('register user form save---------------------------------')
        user.set_password(self.cleaned_data["password2"])
        if commit:
            user.save()
        return user


class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(label='current_password',
                                       widget=forms.PasswordInput(attrs={'class': "input100",
                                                                         'id': 'password1',
                                                                         "type": "password",
                                                                         "name": "password",
                                                                         'placeholder': 'Current Password',
                                                                         }))
    password = forms.CharField(label='new_password', widget=forms.PasswordInput(attrs={'class': "input100",
                                                                                       'id': 'password2',
                                                                                       "type": "password",
                                                                                       "name": "password",
                                                                                       'placeholder': 'New Password',
                                                                                       }))
    repeat_password = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': "input100",
                                                                                          'id': 'password3',
                                                                                          "type": "password",
                                                                                          "name": "password",
                                                                                          'placeholder': 'Repeat Password',
                                                                                          }))


class ResetForgotPasswordForm(forms.Form):
    password = forms.CharField(label='new_password', widget=forms.PasswordInput(attrs={'class': "input100",
                                                                                       'id': 'password',
                                                                                       "type": "password",
                                                                                       "name": "password",
                                                                                       'placeholder': 'New Password',
                                                                                       }))
    repeat_password = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': "input100",
                                                                                          'id': 'password',
                                                                                          "type": "password",
                                                                                          "name": "password",
                                                                                          'placeholder': 'Repeat Password',
                                                                                          }))

    email = forms.CharField(label='email', widget=forms.EmailInput(attrs={'class': "input100",
                                                                          'id': 'email',
                                                                          'type': 'email',
                                                                          'name': 'email',
                                                                          'placeholder': 'Email',
                                                                          }))

users/views.py
from django.contrib import messages
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import render, redirect, HttpResponse
from .forms import CreateUserForm, LoginForm, ChangePasswordForm, ResetForgotPasswordForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login, logout
from django.conf import settings
from django.core.mail import send_mail


def registration(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            return redirect('users:login')
        else:
            return HttpResponse('form is invalid')

    context = {'form': form}

    return render(request, 'users/registration.html', context)


User = get_user_model()


def my_login(request):
    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')

            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)

                return redirect('homagram_app:feed')
            else:
                return HttpResponse('invaild username or password')

    context = {'form': form}

    return render(request, 'users/login.html', context)


def my_logout(request):
    logout(request)
    return redirect('users:login')


@login_required
def change_password(request):
    form = ChangePasswordForm()
    user = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)

        if request.user.check_password(request.POST.get('current_password')):
            if form.is_valid():
                user.set_password(str(form.cleaned_data['password']))
                user.save()
                logout(request)
                messages.info(request, "პაროლი წარმატებით განახლდა!")
                return redirect('users:login')

    context = {'form': form,
               'user': user
               }
    return render(request, 'users/change_password.html', context)


def send_email(email):
    user = User.objects.get(email=email)
    token = default_token_generator.make_token(user)
    reset_url = f"http://127.0.0.1:8000/reset_forgot_password/?email={email}&token={token}"

    subject = "პაროლის აღდგენა"
    message = f'პაროლის გასაახლებლად გთხოვთ გადახვიდეთ ლინკზე: {reset_url}'
    from_email = settings.EMAIL_HOST_USER
    recipient_list = [email]

    send_mail(subject, message, from_email, recipient_list)


def forgot_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')

        if User.objects.filter(email=email).exists():
            send_email(email)
            messages.info(request, "იემილი წარმატებით გაიგზავნა!")

        else:
            messages.info(request, "აღნიშნულ მეილზე აქაუნთი არ არის რეგისტრირებული.")

    return render(request, 'users/forgot_password.html')


def reset_forgot_password(request):
    form = ResetForgotPasswordForm()

    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        form = ResetForgotPasswordForm(request.POST)

        if form.is_valid():
            if str(form.cleaned_data['password']) == str(form.cleaned_data['repeat_password']):
                user.set_password(str(form.cleaned_data['password']))
                user.save()
                logout(request)
                messages.info(request, "პაროლი წარმატებით განახლდა!")
                return redirect('users:login')

    context = {
        'form': form,
    }

    return render(request, 'users/reset_forgot_password.html', context)

users/templates/users/change_password.html
{% extends 'homagram_app/base.html' %}

{% load static %}

	<title>Login V16</title>

{% block content %}

	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'registration/images/bg-01.jpg' %}');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Change Password
				</span>
				<form action="{% url 'users:change_password' %}" method="POST" class="login100-form validate-form p-b-33 p-t-5">
					{% csrf_token %}
					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						{{ form.current_password }}
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						{{ form.password }}
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						{{ form.repeat_password }}
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">
						<button type="submit" class="login100-form-btn">
							Save
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'registration/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'registration/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/js/main.js' %}"></script>

{% endblock %}

users/templates/users/forgot_password.html
{% extends 'homagram_app/base.html' %}

{% load static %}

	<title>Login V16</title>

{% block content %}

<script>
  setTimeout(function() {
	document.getElementById('messages').style.display = 'none';
  }, 3000);
</script>

	<div class="limiter">


		<div class="container-login100" style="background-image: url('{% static 'registration/images/bg-01.jpg' %}');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					{% if messages %}
					<div class="messages-container" id="messages">
						<ul class="messages">
							{% for message in messages %}
							<li class="message {% if message.tags %} {{ message.tags }}{% endif %}">
								{{ message }}
							</li>
							{% endfor %}
						</ul>
					</div>
					{% endif %}

					Email Verification
				</span>
				<form action="{% url 'users:forgot_password' %}" method="POST" class="login100-form validate-form p-b-33 p-t-5">
					{% csrf_token %}
					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input type="email" name="email" id="email" class="input100" placeholder="Email" required>
<!--						{{ form.email }}-->
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">
						<button type="submit" class="login100-form-btn">
							Send
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'registration/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'registration/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/js/main.js' %}"></script>

{% endblock %}

users/templates/users/login.html
{% extends 'homagram_app/base.html' %}

{% load static %}

	<title>Login V16</title>

{% block content %}

	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'registration/images/bg-01.jpg' %}');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					{% if messages %}
					<div class="messages-container" id="messages">
						<ul class="messages">
							{% for message in messages %}
							<li class="message {% if message.tags %} {{ message.tags }}{% endif %}">
								{{ message }}
							</li>
							{% endfor %}
						</ul>
					</div>
					{% endif %}

<script>
  setTimeout(function() {
	document.getElementById('messages').style.display = 'none';
  }, 3000);
</script>

					Account Login
				</span>
				<form action="{% url 'users:login' %}" method="POST" class="login100-form validate-form p-b-33 p-t-5">
					{% csrf_token %}
					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						{{ form.email }}
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						{{ form.password }}
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">
						<a class="signup_button" href="{% url 'users:registration' %}">Sign Up</a>
						<button type="submit" class="login100-form-btn">
							Login
						</button>
						<a class="forgotpass_button" href="{% url 'users:forgot_password' %}">Forgot Password?</a>
					</div>

				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'registration/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'registration/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/js/main.js' %}"></script>

{% endblock %}

users/templates/users/registration.html
{% extends 'homagram_app/base.html' %}

{% load static %}

{% block title %}asdf{% endblock %}


{% block content %}


	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'registration/images/bg-01.jpg' %}');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Account Registration
				</span>
				<form action="{% url 'users:registration' %}" method="POST" enctype="multipart/form-data" class="login100-form validate-form p-b-33 p-t-5">
					{% csrf_token %}

					<div class="right-side">
						<div class="wrap-input100 validate-input" data-validate = "Enter username">
								{{ form.username}}
							{{ form.username.errors }}
							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
							{{ form.first_name }}
							{{ form.first_name.errors }}
							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
							{{ form.last_name }}
							{{ form.last_name.errors }}
							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
							{{ form.email }}
							{{ form.email.errors }}
							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
							{{ form.mobile_number }}
							{{ form.mobile_number.errors }}
							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
							{{ form.about }}
							{{ form.about.errors }}
							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
							{{ form.gender }}
							{{ form.gender.errors }}
							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate = "Enter username">
							  	{{ form.age }}
								{{ form.age.errors }}
							<span class="focus-input100" data-placeholder="&#xe82a;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate="Enter password">
							{{ form.password1 }}
							{{ form.password1.errors }}
							<span class="focus-input100" data-placeholder="&#xe80f;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate="Enter password">
							{{ form.password2 }}
							{{ form.password2.errors }}
							<span class="focus-input100" data-placeholder="&#xe80f;"></span>
						</div>
					</div>

<!--					formaction="{% url 'users:login' %}"-->

					<div class="container-login100-form-btn m-t-32">
						<button type="submit" class="login100-form-btn">
							Sign Up
						</button>
						<a class="signup_button" href="{% url 'users:login' %}">Sing In</a>
					</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'registration/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'registration/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'registration/js/main.js' %}"></script>

{% endblock %}






